# Generated by Django 5.2 on 2025-04-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chambre',
            name='loyer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
