# Generated by Django 5.2 on 2025-04-07 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambres', '0001_initial'),
        ('locataires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locataire',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locataires', to='chambres.chambre'),
        ),
    ]
